name: test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        java: [17, 18]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: test JDK
        id: jdk
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{matrix.java}}
      - name: chmod +x ./gradlew
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew
      - name: build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
